### ISSUE TITLE
pip install eidreader says "No such file or directory: 'setup_info.py'"

### ISSUE THREAD

**Issue by lsaffre** [lino-framework/eidreader#1]
Marc Rabaey reported a problem with eidreader 0.0.1 : you cannot install it:

```
    $ pip install eidreader
    Collecting eidreader
      Downloading eidreader-0.0.1.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-install-2hj2tlzx/eidreader/setup.py", line 3, in <module>
            exec(compile(open(fn, "rb").read(), fn, 'exec'))
        FileNotFoundError: [Errno 2] No such file or directory: 'setup_info.py'

        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-2hj2tlzx/eidreader/

```

**Comment by lsaffre** [comment]
Fixed in version 0.0.4.
